---
# Common installation process for BigData stack

- name: "BIGDATA INSTALL| Install system dependencies"
  ansible.builtin.package:
    name: "{{ bigdata_system_dependencies }}"
    state: present

- name: "BIGDATA INSTALL| Check distribution existence"
  ansible.builtin.stat:
    path: "{{ bigdata_install_dir }}/bin"
  register: _bigdata_install_dir

- name: "BIGDATA INSTALL| Install distribution"
  block:
    - name: "BIGDATA INSTALL BLOCK| Create installation dir"
      ansible.builtin.file:
        path: "{{ bigdata_install_dir }}"
        state: directory
        owner: "{{ bigdata_owner }}"
        group: "{{ bigdata_group }}"
    - name: "BIGDATA INSTALL BLOCK| Unarchive distribution"
      ansible.builtin.unarchive:
        extra_opts: ['--strip-components=1']
        src: "{{ bigdata_url }}"
        dest: "{{ bigdata_install_dir }}"
        owner: "{{ bigdata_owner }}"
        group: "{{ bigdata_group }}"
        remote_src: true
  when:
    - bigdata_install_dir | length > 0
    - bigdata_url | length > 0
    - not _bigdata_install_dir.stat.exists
